services:
  - type: web
    name: health-clinic
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn health_clinic.wsgi:application
    envVars:

      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


