# Generated by Django 5.2.7 on 2025-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-user__username'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group of the patient, e.g., O+, A-', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', help_text='Name of emergency contact person', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of emergency contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, default='', help_text='Insurance or health plan number', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the patient is currently active'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, default='', help_text='Previous conditions, allergies, medications, etc.'),
        ),
    ]
