# Generated by Django 5.2.7 on 2025-11-03 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_alter_patient_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth of the patient.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact number of the patient.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group of the patient, e.g., O+, A-.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', help_text='Name of emergency contact person.', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of emergency contact person.', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, default='', help_text='Insurance or health plan number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the patient is currently active.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(help_text='Linked user account for the patient.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
