# Generated by Django 5.2.7 on 2025-11-03 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['specialization', 'user__last_name'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Doctor Schedule', 'verbose_name_plural': 'Doctor Schedules'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional biography or expertise summary.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Doctor's consultation fee.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if the doctor is currently accepting appointments.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(help_text='Professional license or PRC number.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0–5).', max_digits=3),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(help_text='e.g., Cardiologist, Dentist, Pediatrician.', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(help_text='Linked user account for the doctor.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, help_text='Number of years of medical practice.'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(help_text='The doctor this schedule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor'),
        ),
    ]
